package profileoverlay

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestSourceSelectsExactlyOneProfile 生成内容只 import 请求的形态包，并带「Code generated」
// 头（go vet 与代码审阅都靠它识别生成物）；未知形态在生成前被 registry 拦下。
func TestSourceSelectsExactlyOneProfile(t *testing.T) {
	src, err := Source("minimal")
	require.NoError(t, err)
	assert.Contains(t, src, `"jimu/internal/profiles/minimal"`)
	assert.NotContains(t, src, `"jimu/internal/profiles/full"`)
	assert.Contains(t, src, "package active")
	assert.Contains(t, src, "func Assembly() assembly.Assembly { return minimal.Assembly() }")
	assert.Contains(t, src, "Code generated by tools/profileoverlay")

	_, err = Source("ghost")
	require.ErrorContains(t, err, `unknown profile "ghost"`)
}

// TestDirIsProfileScoped 产物目录按形态隔离：不同形态并发构建不得共享 active.go。
func TestDirIsProfileScoped(t *testing.T) {
	root := t.TempDir()
	assert.Equal(t, filepath.Join(root, ".overlay", "minimal"), Dir(root, "minimal"))
	assert.NotEqual(t, Dir(root, "minimal"), Dir(root, "full"))
}

// TestReplaceMapPointsActiveAtTheGeneratedContent 内存 overlay 只替换选点文件，键为绝对
// 路径（go/packages 的 Config.Overlay 约定），值与 Source 逐字节相同。
func TestReplaceMapPointsActiveAtTheGeneratedContent(t *testing.T) {
	root := t.TempDir()
	overlay, err := ReplaceMap(root, "minimal")
	require.NoError(t, err)
	require.Len(t, overlay, 1)

	src, err := Source("minimal")
	require.NoError(t, err)
	content, ok := overlay[filepath.Join(root, "internal", "profiles", "active", "assembly.go")]
	require.True(t, ok)
	assert.Equal(t, src, string(content))

	_, err = ReplaceMap(root, "ghost")
	require.ErrorContains(t, err, `unknown profile "ghost"`)
}

// TestWriteFilesWritesBothArtifactsPerProfile 落盘产物在 `.overlay/<profile>/` 下：
// overlay JSON 的 Replace 把仓库选点文件映射到同目录的 active.go，active.go 与 Source
// 逐字节相同；返回的是 JSON 的绝对路径（go build -overlay= 的入参）。
func TestWriteFilesWritesBothArtifactsPerProfile(t *testing.T) {
	root := t.TempDir()
	jsonPath, err := WriteFiles(root, "enterprise")
	require.NoError(t, err)
	assert.Equal(t, filepath.Join(root, ".overlay", "enterprise", "overlay.json"), jsonPath)

	src, err := Source("enterprise")
	require.NoError(t, err)
	active, err := os.ReadFile(filepath.Join(root, ".overlay", "enterprise", "active.go"))
	require.NoError(t, err)
	assert.Equal(t, src, string(active))

	content, err := os.ReadFile(jsonPath)
	require.NoError(t, err)
	var cfg struct{ Replace map[string]string }
	require.NoError(t, json.Unmarshal(content, &cfg))
	assert.Equal(t,
		filepath.Join(root, ".overlay", "enterprise", "active.go"),
		cfg.Replace[filepath.Join(root, "internal", "profiles", "active", "assembly.go")])
}

// TestWriteFilesRejectsUnknownProfileBeforeTouchingDisk 非法形态名必须在写盘前失败，
// 不留半成品目录（make 靠非零退出终止，而不是留下空的 -overlay=）。
func TestWriteFilesRejectsUnknownProfileBeforeTouchingDisk(t *testing.T) {
	root := t.TempDir()
	_, err := WriteFiles(root, "ghost")
	require.ErrorContains(t, err, `unknown profile "ghost"`)
	_, statErr := os.Stat(filepath.Join(root, ".overlay"))
	assert.True(t, os.IsNotExist(statErr), ".overlay 不应被创建: %v", statErr)
}

// TestGuardedEntryPointsRejectPathTraversal Dir 是纯拼接、不做白名单校验（见其文档前置条件）；
// 越出 .overlay/ 的形态名必须被落盘/内存两条入口拦下，且不留任何目录。
func TestGuardedEntryPointsRejectPathTraversal(t *testing.T) {
	root := t.TempDir()
	const evil = "../../escape"

	_, err := Source(evil)
	require.ErrorContains(t, err, `unknown profile "../../escape"`)

	_, err = ReplaceMap(root, evil)
	require.ErrorContains(t, err, `unknown profile "../../escape"`)

	_, err = WriteFiles(root, evil)
	require.ErrorContains(t, err, `unknown profile "../../escape"`)

	_, statErr := os.Stat(filepath.Join(root, ".overlay"))
	assert.True(t, os.IsNotExist(statErr), ".overlay 不应被创建: %v", statErr)
	_, statErr = os.Stat(filepath.Join(filepath.Dir(root), "escape"))
	assert.True(t, os.IsNotExist(statErr), "不得在仓库外创建目录: %v", statErr)
}
