// Package profileoverlay 是「构建期形态选点」overlay 的唯一真源：替换内容模板与产物
// 路径都在这里，供 tools/profileoverlay（命令行）、tools/checkcapabilities（门禁）与
// tools/composereport（报告）共用 —— 三处各留一份副本时，门禁与报告度量的就不再是出货
// 二进制（模板漂移而门禁仍全绿）。
//
// overlay 把 internal/profiles/active/assembly.go 在**本次构建**中替换为「只选一个形态」
// 的版本，不改动工作区里的任何受版本控制的文件。
package profileoverlay

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"jimu/internal/profiles/registry"
)

// overlayDir 产物根目录（相对仓库根，gitignored）。
const overlayDir = ".overlay"

// activePath 被替换的选点文件（相对仓库根）。
var activePath = filepath.Join("internal", "profiles", "active", "assembly.go")

// Source 返回选点文件的替代内容（含「Code generated」头）；形态名经 registry 白名单校验。
func Source(profile string) (string, error) {
	if _, err := registry.Lookup(profile); err != nil {
		return "", err
	}
	return fmt.Sprintf(`// Code generated by tools/profileoverlay; DO NOT EDIT.
// 本文件是 overlay 替换版：把 internal/profiles/active 的选点指向 %s 形态。
package active

import (
	"jimu/internal/assembly"
	"jimu/internal/profiles/%s"
)

// Assembly 返回本次构建选中的形态。
func Assembly() assembly.Assembly { return %s.Assembly() }
`, profile, profile, profile), nil
}

// ReplaceMap 返回内存 overlay（键值均为绝对路径）：键是被替换的选点文件，值是生成内容。
// `golang.org/x/tools/go/packages` 的 Config.Overlay 与 go build 的 -overlay 用同一约定。
func ReplaceMap(root, profile string) (map[string][]byte, error) {
	src, err := Source(profile)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{filepath.Join(root, activePath): []byte(src)}, nil
}

// Dir 返回该形态的产物目录：按形态隔离（`.overlay/<profile>/`），不同形态的并发构建不再
// 互踩 active.go —— 共享路径会**静默产出错误形态的二进制**。
//
// 前置条件：profile 必须是 registry 认识的形态名。本函数是纯路径拼接、不做白名单校验（签名
// 无 error 可回报），传未校验的输入（如 `../..`）会越出 .overlay/。落盘与内存 overlay 一律
// 走 WriteFiles/ReplaceMap —— 它们先经 Source 校验形态名，非法输入在触碰磁盘前失败。
func Dir(root, profile string) string {
	return filepath.Join(root, overlayDir, profile)
}

// WriteFiles 写 `.overlay/<profile>/{active.go,overlay.json}`，返回 overlay JSON 的绝对路径
// （`go build -overlay=` 与 Dockerfile 都直接消费它）。形态名非法时在写盘前失败。
func WriteFiles(root, profile string) (string, error) {
	src, err := Source(profile)
	if err != nil {
		return "", err
	}
	dir := Dir(root, profile)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	activeFile := filepath.Join(dir, "active.go")
	if err := os.WriteFile(activeFile, []byte(src), 0o644); err != nil {
		return "", err
	}
	cfg := struct {
		Replace map[string]string `json:"Replace"`
	}{Replace: map[string]string{filepath.Join(root, activePath): activeFile}}
	content, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return "", err
	}
	jsonPath := filepath.Join(dir, "overlay.json")
	if err := os.WriteFile(jsonPath, append(content, '\n'), 0o644); err != nil {
		return "", err
	}
	return jsonPath, nil
}
