apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jimu.labels" . | nindent 4 }}
type: Opaque
stringData:
  db_password: "REPLACE_WITH_ACTUAL_PASSWORD"
  redis_password: "REPLACE_WITH_ACTUAL_PASSWORD"
  jwt_secret: "REPLACE_WITH_AT_LEAST_32_CHARACTERS_RANDOM"
