apiVersion: v1
kind: Secret
metadata:
  name: jimu-secrets
  namespace: jimu
type: Opaque
stringData:
  # 覆盖 app.prod.yaml 中的配置
  DB_HOST: "mariadb.jimu.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "jimu"
  DB_PASSWORD: "change-me-in-production"
  DB_NAME: "jimu"
  REDIS_ADDR: "redis.jimu.svc.cluster.local:6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  JWT_SECRET: "change-me-use-at-least-32-characters"
