-- +goose Up
CREATE TABLE scheduled_jobs (
    id VARCHAR(64) NOT NULL COMMENT '任务 ID',
    name VARCHAR(128) NOT NULL COMMENT '任务名称',
    cron VARCHAR(64) NOT NULL COMMENT 'cron 表达式',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME DEFAULT NULL COMMENT '软删除时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='定时任务定义表';

-- +goose Down
DROP TABLE scheduled_jobs;
