-- +goose Up
CREATE TABLE IF NOT EXISTS capmig_solo_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL
);
-- +goose Down
DROP TABLE IF EXISTS capmig_solo_items;
