-- +goose Up
CREATE TABLE IF NOT EXISTS capmig_solo_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(64) NOT NULL
);
-- +goose Down
DROP TABLE IF EXISTS capmig_solo_tags;
