package generator

import (
	"crypto/sha256"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"jimu/tools/generator/frameworkmanifest"
	"jimu/tools/generator/manifest"
	"jimu/tools/generator/workspace"
)

// 本文件实现 `jimu capability add <name>`（P2.7 Task 7）：在**已生成项目**上增量加入一个能力。
//
// 合并口径（S8）：读 marker 的声明集/驱动集 → 并入新能力（校验 Requires 全在声明集内，缺则报错
// 并提示先加依赖；**不自动补全闭包**）→ 经 CapabilityRoots **重算** Copy/MigrationOnly/Known
// （marker.capabilities 只是声明集，不含迁移携带能力 —— T3 裁定 7）→ 用与 `jimu new` **同一条**
// renderDerivedAll 管线在暂存目录重渲染 → 配置段以生成项目现有文件为底合并（裁定 ⑬）→ 按差异
// 逐文件落盘（先备份、失败回滚）。
//
// 确定性（S8）：产物只是「声明集 + module」的纯函数，故同一集合重跑逐字节等价，二次 add 无改动。

// AddOptions 是 `jimu capability add` 的全部输入。
type AddOptions struct {
	Name   string // 要加入的能力名（框架全量集合：catalog 18 ∪ Ungated 7）
	From   string // 框架源根；空则从当前 jimu checkout 解析
	Dir    string // 生成项目根
	Module string // 覆盖 manifest 里的 module（默认取 manifest rewrite）
	Force  bool   // 能力已在 entries 里时也允许（重建该能力，只对生成器产物）
	DryRun bool   // 只报计划，不落盘
}

// AddCapability 往已生成项目追加一个能力。
//
// 校验（全部在看盘之前）：能力名属于框架全量集合；Requires 必须已全在声明集里（缺则提示
// `jimu capability add <dep>`，**不自动补全**）；能力已在 entries（声明集 ∪ 迁移携带集）里时
// 报错，除非 --force。
//
// 落盘：在 <dir> 同级建暂存目录，用 renderDerivedAll 重渲染新集合的全部产物，随后
//
//	① 配置段合并：configs/app.yaml、configs/app.prod.yaml、deploy/helm/values.yaml 以生成项目
//	   **现有**文件为底，用重渲染结果补齐新增段/键（裁定 ⑬ —— 绝不整份覆盖用户手改的段值）；
//	② 与现有项目做差异比对；--dry-run 只返回差异清单；
//	③ 只把差异里的文件逐个落盘（被改写的先备份），任一步失败即回滚到调用前。
//
// 因为落盘是**逐文件**的（不是整目录替换），生成项目里用户自有的文件永远不会被碰到。
//
// 生成文件带 `// Code generated by jimu new; DO NOT EDIT.`（手改生成文件会被覆盖）；配置段值
// 与用户自有文件必须保留。自检（go build / checkcapabilities）归 T8 的 SelfCheck，本函数不做
// （new 同样不在此处自检）。
func AddCapability(opts AddOptions) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("capability name must not be empty")
	}
	dir := absPath(opts.Dir)
	previous, err := workspace.LoadProjectManifest(dir)
	if err != nil {
		return nil, err
	}
	root := opts.From
	if root == "" {
		root, err = frameworkRoot()
		if err != nil {
			return nil, fmt.Errorf("framework source root is required for capability add: pass --from=<jimu checkout>: %w", err)
		}
	}
	root, err = filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolve framework source root: %w", err)
	}
	next, err := frameworkmanifest.ExportForAdd(root, previous, name, opts.Force)
	if err != nil {
		return nil, err
	}
	module := opts.Module
	if module == "" {
		module = moduleFromManifest(next)
	}
	if module == "" {
		return nil, fmt.Errorf("manifest does not declare a module rewrite")
	}
	if opts.Module != "" {
		for i := range next.Rewrites {
			if next.Rewrites[i].Kind == "module" {
				next.Rewrites[i].To = opts.Module
			}
		}
		next.Digest = ""
		digest, err := manifest.Digest(next)
		if err != nil {
			return nil, err
		}
		next.Digest = digest
	}
	_, reportErr := os.Stat(filepath.Join(dir, filepath.FromSlash("docs/profiles/generated-report.md")))
	workspaceInstall := workspace.InstallFile
	workspace.InstallFile = installFile
	defer func() { workspace.InstallFile = workspaceInstall }()
	updated, err := workspace.Update(previous, next, workspace.UpdateOptions{
		ProjectRoot: dir,
		SourceRoot:  root,
		Module:      module,
		Force:       opts.Force,
		DryRun:      opts.DryRun,
		Report:      reportErr == nil,
	})
	if err != nil {
		return nil, err
	}
	return &Result{
		Dir:          updated.Target,
		Module:       updated.Module,
		Shape:        next.Selection.Shape,
		Capabilities: slices.Clone(next.Selection.Capabilities),
		CopySet:      manifestCapabilityNames(next),
		Drivers:      flattenDrivers(next.Selection.Drivers),
		Assets:       manifestAssetNames(next),
		Changed:      slices.Clone(updated.Changed),
		Files:        slices.Clone(updated.Files),
		FileCount:    updated.FileCount,
	}, nil
}

func moduleFromManifest(doc manifest.Document) string {
	for _, rewrite := range doc.Rewrites {
		if rewrite.Kind == "module" {
			return rewrite.To
		}
	}
	return ""
}

// mergeGeneratedConfigs 落实裁定 ⑬：configs/*.yaml 与 values.yaml 以生成项目**现有**文件为底，
// 用重渲染结果补齐现有文件里没有的段/键。绝不整份覆盖 —— 那会静默抹掉用户手改的段值。
//
// 现有文件不存在时保持重渲染结果（首次生成的完整产物）。
func mergeGeneratedConfigs(dir, staging string) error {
	rels := append(configFiles(), valuesRelPath)
	for _, rel := range rels {
		existing, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(rel)))
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("read existing %s: %w", rel, err)
		}
		freshPath := filepath.Join(staging, filepath.FromSlash(rel))
		fresh, err := os.ReadFile(freshPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue // 本选择不含该文件（如无 helm chart）
			}
			return fmt.Errorf("read rendered %s: %w", rel, err)
		}
		merged, err := MergeSectionBlocks(existing, fresh)
		if err != nil {
			return fmt.Errorf("merge %s: %w", rel, err)
		}
		if err := writeFile(freshPath, merged, 0o644); err != nil {
			return fmt.Errorf("write merged %s: %w", rel, err)
		}
	}
	return nil
}

// MergeSectionBlocks 以 base（生成项目现有内容）为底，把 fresh（蓝本重渲染的同名段）里 base
// 没有的顶层段追加进来；同名段一律用 base 原文（保住用户手改的段值），base 独有的段（用户自有）
// 也一律保留。两边的段解析都走 SectionBlocks —— 解析失败即报错，绝不静默丢内容。
//
// 接缝：base 若无尾换行（用户手改常见的形态），追加前**必须**补一个换行 —— 否则 base 末行的段值
// 会与 fresh 的首个段键粘成一行（`...持久化）# 文件存储配置`），静默毁掉两段内容。
func MergeSectionBlocks(base, fresh []byte) ([]byte, error) {
	baseKeys, baseBlocks, err := SectionBlocks(base)
	if err != nil {
		return nil, err
	}
	freshKeys, freshBlocks, err := SectionBlocks(fresh)
	if err != nil {
		return nil, err
	}
	have := make(map[string]bool, len(baseKeys))
	for _, key := range baseKeys {
		have[key] = true
	}
	var out strings.Builder
	out.Grow(len(base) + len(fresh))
	lastIsNewline := true // 空输出视为已换行：文件头不补空行
	write := func(block string) {
		if block == "" {
			return
		}
		if !lastIsNewline && block[0] != '\n' {
			out.WriteByte('\n')
		}
		out.WriteString(block)
		lastIsNewline = block[len(block)-1] == '\n'
	}
	for i := range baseKeys {
		write(baseBlocks[i])
	}
	for i, key := range freshKeys {
		if key == "" || have[key] {
			continue
		}
		write(freshBlocks[i])
	}
	return []byte(out.String()), nil
}

// changeSet 返回暂存树相对现有项目的差异（排序）：新增、内容不同、以及旧生成产物里已被移除的文件。
// 只比内容，不比 mtime —— add 的幂等判据是「逐字节等价」。`generated`（旧 marker.files）限定了
// 「移除」的候选：用户自有文件不在其中，永远不会被删除。
func changeSet(dir, staging string, generated []string) ([]string, error) {
	oldHashes, err := treeHashes(dir)
	if err != nil {
		return nil, err
	}
	newHashes, err := treeHashes(staging)
	if err != nil {
		return nil, err
	}
	gen := make(map[string]bool, len(generated))
	for _, rel := range generated {
		gen[rel] = true
	}
	var changed []string
	for rel, hash := range newHashes {
		if old, ok := oldHashes[rel]; !ok || old != hash {
			changed = append(changed, rel)
		}
	}
	for rel := range oldHashes {
		if _, ok := newHashes[rel]; !ok && gen[rel] {
			changed = append(changed, rel)
		}
	}
	sort.Strings(changed)
	return changed, nil
}

// treeHashes 返回 相对路径 → 内容 sha256。
func treeHashes(root string) (map[string]string, error) {
	out := map[string]string{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == ".git" {
				return fs.SkipDir
			}
			return nil
		}
		content, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		out[relPath(root, p)] = fmt.Sprintf("%x", sha256.Sum256(content))
		return nil
	})
	return out, err
}

// installFile 是 installStaged 的落盘注入点（测试用它注入中途失败以验证回滚）。
var installFile = copyOneFile

// installStaged 把 changed 里的文件逐个落盘：被改写/被移除的先把原文件搬进备份目录，任一失败即
// 反向回滚（恢复备份、删除本次新增），成功后删备份。**不整体 rename 项目根** —— 调用者的 cwd
// 很可能就是 <dir>（`cd proj && jimu capability add x`），目录级替换会把 shell 留在已删除的 inode 上。
func installStaged(dir, staging string, changed, generated []string) error {
	backup, err := os.MkdirTemp(filepath.Dir(dir), filepath.Base(dir)+".bak-")
	if err != nil {
		return fmt.Errorf("create backup directory: %w", err)
	}
	defer func() { _ = os.RemoveAll(backup) }()

	type op struct {
		rel     string
		restore bool // true = 原文件在备份里（回滚时恢复），false = 本次新增（回滚时删除）
	}
	var ops []op
	rollback := func() {
		for i := len(ops) - 1; i >= 0; i-- {
			o := ops[i]
			if o.restore {
				if err := copyOneFile(backup, dir, o.rel); err != nil {
					// 回滚本身失败已无法挽回：把错误留给调用方时也提示备份目录位置。
					fmt.Fprintf(os.Stderr, "rollback %s failed: %v\n", o.rel, err)
				}
				continue
			}
			_ = os.Remove(filepath.Join(dir, filepath.FromSlash(o.rel)))
		}
	}
	fail := func(format string, args ...any) error {
		rollback()
		return fmt.Errorf(format, args...)
	}

	gen := make(map[string]bool, len(generated))
	for _, rel := range generated {
		gen[rel] = true
	}
	for _, rel := range changed {
		src := filepath.Join(staging, filepath.FromSlash(rel))
		dst := filepath.Join(dir, filepath.FromSlash(rel))
		if _, err := os.Stat(src); os.IsNotExist(err) {
			if !gen[rel] {
				continue // 只删生成器产物，用户文件不在此列（changeSet 已保证）
			}
			if err := moveToBackup(dst, backup, rel); err != nil {
				return fail("remove %s: %w", rel, err)
			}
			ops = append(ops, op{rel: rel, restore: true})
			continue
		}
		existed := false
		if _, err := os.Stat(dst); err == nil {
			existed = true
			if err := copyOneFile(dir, backup, rel); err != nil {
				return fail("back up %s: %w", rel, err)
			}
		}
		if err := installFile(staging, dir, rel); err != nil {
			return fail("install %s: %w", rel, err)
		}
		ops = append(ops, op{rel: rel, restore: existed})
	}
	return nil
}

// moveToBackup 把 dst（生成项目里的相对路径）搬到备份目录的同名位置。
func moveToBackup(dst, backup, rel string) error {
	target := filepath.Join(backup, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.Rename(dst, target); err != nil {
		return err
	}
	return nil
}
