package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"jimu/tools/generator/frameworkmanifest"
	"jimu/tools/generator/manifest"
	"jimu/tools/generator/workspace"
)

// 本文件实现 `jimu capability add <name>`（P2.7 Task 7）：在**已生成项目**上增量加入一个能力。
//
// 合并口径（S8）：读 marker 的声明集/驱动集 → 并入新能力（校验 Requires 全在声明集内，缺则报错
// 并提示先加依赖；**不自动补全闭包**）→ 经 manifest pipeline 重算 Copy/MigrationOnly/Known
// （marker.capabilities 只是声明集，不含迁移携带能力 —— T3 裁定 7）→ 在暂存目录重渲染并合并配置
// → 按差异逐文件落盘（先备份、失败回滚）。
//
// 确定性（S8）：产物只是「声明集 + module」的纯函数，故同一集合重跑逐字节等价，二次 add 无改动。

// AddOptions 是 `jimu capability add` 的全部输入。
type AddOptions struct {
	Name   string // 要加入的能力名（框架全量集合）
	From   string // 框架源根；空则从当前 jimu checkout 解析
	Dir    string // 生成项目根
	Module string // 覆盖 manifest 里的 module（默认取 manifest rewrite）
	Force  bool   // 能力已在 entries 里时也允许（重建该能力，只对生成器产物）
	DryRun bool   // 只报计划，不落盘
}

// AddCapability 往已生成项目追加一个能力。
//
// 校验（全部在看盘之前）：能力名属于框架全量集合；Requires 必须已全在声明集里（缺则提示
// `jimu capability add <dep>`，**不自动补全**）；能力已在 entries（声明集 ∪ 迁移携带集）里时
// 报错，除非 --force。
//
// 落盘：在 <dir> 同级建暂存目录，用 renderDerivedAll 重渲染新集合的全部产物，随后
//
//	① 配置段合并：configs/app.yaml、configs/app.prod.yaml、deploy/helm/values.yaml 以生成项目
//	   **现有**文件为底，用重渲染结果补齐新增段/键（裁定 ⑬ —— 绝不整份覆盖用户手改的段值）；
//	② 与现有项目做差异比对；--dry-run 只返回差异清单；
//	③ 只把差异里的文件逐个落盘（被改写的先备份），任一步失败即回滚到调用前。
//
// 因为落盘是**逐文件**的（不是整目录替换），生成项目里用户自有的文件永远不会被碰到。
//
// 生成文件带 `// Code generated by jimu new; DO NOT EDIT.`（手改生成文件会被覆盖）；配置段值
// 与用户自有文件必须保留。自检（go build / checkcapabilities）归 workspace，本函数不做。
func AddCapability(opts AddOptions) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("capability name must not be empty")
	}
	dir := absPath(opts.Dir)
	previous, err := workspace.LoadProjectManifest(dir)
	if err != nil {
		return nil, err
	}
	root := opts.From
	if root == "" {
		root, err = frameworkRoot()
		if err != nil {
			return nil, fmt.Errorf("framework source root is required for capability add: pass --from=<jimu checkout>: %w", err)
		}
	}
	root, err = filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolve framework source root: %w", err)
	}
	next, err := frameworkmanifest.ExportForAdd(root, previous, name, opts.Force)
	if err != nil {
		return nil, err
	}
	module := opts.Module
	if module == "" {
		module = moduleFromManifest(next)
	}
	if module == "" {
		return nil, fmt.Errorf("manifest does not declare a module rewrite")
	}
	if opts.Module != "" {
		for i := range next.Rewrites {
			if next.Rewrites[i].Kind == "module" {
				next.Rewrites[i].To = opts.Module
			}
		}
		next.Digest = ""
		digest, err := manifest.Digest(next)
		if err != nil {
			return nil, err
		}
		next.Digest = digest
	}
	_, reportErr := os.Stat(filepath.Join(dir, filepath.FromSlash("docs/profiles/generated-report.md")))
	workspaceInstall := workspace.InstallFile
	workspace.InstallFile = installFile
	defer func() { workspace.InstallFile = workspaceInstall }()
	updated, err := workspace.Update(previous, next, workspace.UpdateOptions{
		ProjectRoot: dir,
		SourceRoot:  root,
		Module:      module,
		Force:       opts.Force,
		DryRun:      opts.DryRun,
		Report:      reportErr == nil,
	})
	if err != nil {
		return nil, err
	}
	return &Result{
		Dir:          updated.Target,
		Module:       updated.Module,
		Shape:        next.Selection.Shape,
		Capabilities: slices.Clone(next.Selection.Capabilities),
		CopySet:      manifestCapabilityNames(next),
		Drivers:      flattenDrivers(next.Selection.Drivers),
		Assets:       manifestAssetNames(next),
		Changed:      slices.Clone(updated.Changed),
		Files:        slices.Clone(updated.Files),
		FileCount:    updated.FileCount,
	}, nil
}

func moduleFromManifest(doc manifest.Document) string {
	for _, rewrite := range doc.Rewrites {
		if rewrite.Kind == "module" {
			return rewrite.To
		}
	}
	return ""
}

// MergeSectionBlocks 以 base（生成项目现有内容）为底，把 fresh（蓝本重渲染的同名段）里 base
// 没有的顶层段追加进来；同名段一律用 base 原文（保住用户手改的段值），base 独有的段（用户自有）
// 也一律保留。两边的段解析都走 SectionBlocks —— 解析失败即报错，绝不静默丢内容。
//
// 接缝：base 若无尾换行（用户手改常见的形态），追加前**必须**补一个换行 —— 否则 base 末行的段值
// 会与 fresh 的首个段键粘成一行（`...持久化）# 文件存储配置`），静默毁掉两段内容。
func MergeSectionBlocks(base, fresh []byte) ([]byte, error) {
	baseKeys, baseBlocks, err := SectionBlocks(base)
	if err != nil {
		return nil, err
	}
	freshKeys, freshBlocks, err := SectionBlocks(fresh)
	if err != nil {
		return nil, err
	}
	have := make(map[string]bool, len(baseKeys))
	for _, key := range baseKeys {
		have[key] = true
	}
	var out strings.Builder
	out.Grow(len(base) + len(fresh))
	lastIsNewline := true // 空输出视为已换行：文件头不补空行
	write := func(block string) {
		if block == "" {
			return
		}
		if !lastIsNewline && block[0] != '\n' {
			out.WriteByte('\n')
		}
		out.WriteString(block)
		lastIsNewline = block[len(block)-1] == '\n'
	}
	for i := range baseKeys {
		write(baseBlocks[i])
	}
	for i, key := range freshKeys {
		if key == "" || have[key] {
			continue
		}
		write(freshBlocks[i])
	}
	return []byte(out.String()), nil
}

// installFile 是 workspace.Update 的落盘注入点（测试用它注入中途失败以验证回滚）。
var installFile = copyOneFile
