package generator

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"jimu/internal/capabilities/catalog"
	"jimu/internal/contract"
)

// 本文件实现 `jimu capability add <name>`（P2.7 Task 7）：在**已生成项目**上增量加入一个能力。
//
// 合并口径（S8）：读 marker 的声明集/驱动集 → 并入新能力（校验 Requires 全在声明集内，缺则报错
// 并提示先加依赖；**不自动补全闭包**）→ 经 CapabilityRoots **重算** Copy/MigrationOnly/Known
// （marker.capabilities 只是声明集，不含迁移携带能力 —— T3 裁定 7）→ 用与 `jimu new` **同一条**
// renderDerivedAll 管线在暂存目录重渲染 → 配置段以生成项目现有文件为底合并（裁定 ⑬）→ 按差异
// 逐文件落盘（先备份、失败回滚）。
//
// 确定性（S8）：产物只是「声明集 + module」的纯函数，故同一集合重跑逐字节等价，二次 add 无改动。

// AddOptions 是 `jimu capability add` 的全部输入。
type AddOptions struct {
	Name   string // 要加入的能力名（框架全量集合：catalog 18 ∪ Ungated 7）
	From   string // 框架源根；空则取 marker.SourceRoot（S7）
	Dir    string // 生成项目根
	Module string // 覆盖 marker 里的 module（默认取 marker.Module）
	Force  bool   // 能力已在 entries 里时也允许（重建该能力，只对生成器产物）
	DryRun bool   // 只报计划，不落盘
}

// LoadMarker 读 <dir>/.jimu-generated；没有该文件即说明目录不是生成器产物（fail-closed，
// 绝不按猜测重渲染任意目录）。
func LoadMarker(dir string) (*Marker, error) {
	path := filepath.Join(dir, markerFile)
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("%s is not a jimu-generated project: missing %s (run jimu new first)", filepathSlash(dir), markerFile)
		}
		return nil, fmt.Errorf("read %s: %w", filepathSlash(path), err)
	}
	var m Marker
	if err := json.Unmarshal(content, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", filepathSlash(path), err)
	}
	if !strings.HasPrefix(m.Generator, "jimu") {
		return nil, fmt.Errorf("%s: %s is not a jimu marker (generator=%q)", filepathSlash(dir), markerFile, m.Generator)
	}
	if m.Module == "" {
		return nil, fmt.Errorf("%s: %s has no module field", filepathSlash(dir), markerFile)
	}
	return &m, nil
}

// Save 把 marker 写回 <dir>/.jimu-generated（缩进 JSON + 尾换行，与 jimu new 同格式）。
func (m *Marker) Save(dir string) error {
	content, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return fmt.Errorf("encode %s: %w", markerFile, err)
	}
	if err := os.WriteFile(filepath.Join(dir, markerFile), append(content, '\n'), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", markerFile, err)
	}
	return nil
}

// AddCapability 往已生成项目追加一个能力。
//
// 校验（全部在看盘之前）：能力名属于框架全量集合；Requires 必须已全在声明集里（缺则提示
// `jimu capability add <dep>`，**不自动补全**）；能力已在 entries（声明集 ∪ 迁移携带集）里时
// 报错，除非 --force。
//
// 落盘：在 <dir> 同级建暂存目录，用 renderDerivedAll 重渲染新集合的全部产物，随后
//
//	① 配置段合并：configs/app.yaml、configs/app.prod.yaml、deploy/helm/values.yaml 以生成项目
//	   **现有**文件为底，用重渲染结果补齐新增段/键（裁定 ⑬ —— 绝不整份覆盖用户手改的段值）；
//	② 与现有项目做差异比对；--dry-run 只返回差异清单；
//	③ 只把差异里的文件逐个落盘（被改写的先备份），任一步失败即回滚到调用前。
//
// 因为落盘是**逐文件**的（不是整目录替换），生成项目里用户自有的文件永远不会被碰到，也不会进
// marker.files（writeMarker 只走暂存树，只看得见生成产物）。
//
// 生成文件带 `// Code generated by jimu new; DO NOT EDIT.`（手改生成文件会被覆盖）；配置段值
// 与用户自有文件必须保留。自检（go build / checkcapabilities）归 T8 的 SelfCheck，本函数不做
// （new 同样不在此处自检）。
func AddCapability(opts AddOptions) (*Result, error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return nil, fmt.Errorf("capability name must not be empty")
	}
	dir := absPath(opts.Dir)
	m, err := LoadMarker(dir)
	if err != nil {
		return nil, err
	}
	root, err := resolveSourceRoot(opts.From, m)
	if err != nil {
		return nil, err
	}
	module := m.Module
	if opts.Module != "" {
		module = opts.Module
	}
	if err := validateModule(module); err != nil {
		return nil, err
	}

	set, err := newCapabilitySet(root, m, name, opts.Force)
	if err != nil {
		return nil, err
	}

	staging, err := os.MkdirTemp(filepath.Dir(dir), filepath.Base(dir)+".tmp-")
	if err != nil {
		return nil, fmt.Errorf("create staging directory: %w", err)
	}
	defer func() { _ = os.RemoveAll(staging) }()
	if err := renderDerivedAll(root, staging, set, module); err != nil {
		return nil, err
	}
	// ①：先合并配置段（以生成项目现有文件为底）。用户自有文件不需要搬运 —— 逐文件落盘不会碰它们。
	if err := mergeGeneratedConfigs(dir, staging); err != nil {
		return nil, err
	}
	changed, err := changeSet(dir, staging, m.Files)
	if err != nil {
		return nil, err
	}
	assets, err := AssetsFor(set)
	if err != nil {
		return nil, err
	}
	res := &Result{
		Dir:          dir,
		Module:       module,
		Shape:        set.Shape,
		Capabilities: slices.Clone(set.Declared),
		Drivers:      flattenDrivers(set.Drivers),
		Assets:       assets,
		Changed:      changed,
		FileCount:    len(changed),
	}
	if opts.DryRun || len(changed) == 0 {
		return res, nil
	}
	if err := installStaged(dir, staging, changed, m.Files); err != nil {
		return nil, err
	}
	return res, nil
}

// resolveSourceRoot 定位框架源根：--from 优先，否则取 marker.SourceRoot（S7）。两条路径都必须
// 真的是框架仓（go.mod 的 module 为 jimu），否则 fail-closed —— 绝不拿错的源目录去重渲染。
func resolveSourceRoot(from string, m *Marker) (string, error) {
	root := from
	if root == "" {
		root = m.SourceRoot
	}
	if root == "" {
		return "", fmt.Errorf("no framework source root: pass --from or regenerate with a version that records sourceRoot in %s", markerFile)
	}
	root = absPath(root)
	mod, err := moduleOf(filepath.Join(root, "go.mod"))
	if err != nil || mod != frameworkModule {
		return "", fmt.Errorf("framework source root %s does not declare module %s; pass --from=<jimu checkout>", filepathSlash(root), frameworkModule)
	}
	return root, nil
}

// newCapabilitySet 把「marker 声明集 + 一个能力」重算成完整的 CapabilitySet。
//
// 硬输入（T3 裁定 7 / 裁定 ⑬）：必须经 CapabilityRoots 重算 Copy/MigrationOnly/Known ——
// marker.capabilities 只是声明集，迁移携带能力（如 tenant）不在其中。声明序沿用
// ParseCapabilitySet 的规则：catalog 拓扑序 + 非 catalog（Ungated）追加在尾部。
func newCapabilitySet(root string, m *Marker, name string, force bool) (CapabilitySet, error) {
	descs, _, err := capabilityDescriptors(root)
	if err != nil {
		return CapabilitySet{}, err
	}
	byName := make(map[string]contract.Descriptor, len(descs))
	for _, d := range descs {
		byName[d.Name] = d
	}
	desc, ok := byName[name]
	if !ok {
		return CapabilitySet{}, fmt.Errorf("unknown capability %q (available: %s)", name, strings.Join(knownCapabilityNames(descs), ", "))
	}
	declaredSet := make(map[string]bool, len(m.Capabilities)+1)
	for _, c := range m.Capabilities {
		declaredSet[c] = true
	}
	// 已在 entries 里 = 已声明（装配）或已随迁移携带（如 minimal 的 tenant）。两者文案必须分开：
	// 迁移携带的能力有 migrations/domain 但没有实现，--force 的语义是「提升为完整声明能力」。
	if alreadyPresent(name, declaredSet) && !force {
		if declaredSet[name] {
			return CapabilitySet{}, fmt.Errorf("capability %q is already present in %s as a declared capability; pass --force to rebuild it", name, filepathSlash(m.Module))
		}
		return CapabilitySet{}, fmt.Errorf("capability %q is already present in %s, but only as a migration carry (no implementation is copied yet); pass --force to promote it to a full declared capability", name, filepathSlash(m.Module))
	}
	declaredSet[name] = true
	// 硬输入 ④：不做依赖闭包自动补全 —— 缺哪个依赖就报哪个，由用户决定是否显式加入。
	for _, dep := range desc.Requires {
		if !declaredSet[dep] {
			return CapabilitySet{}, fmt.Errorf("capability %q requires %q, which is not in the project — add it first: jimu capability add %s", name, dep, dep)
		}
	}

	inCatalog := make(map[string]bool, len(catalog.All()))
	for _, d := range catalog.All() {
		inCatalog[d.Name] = true
	}
	declared, ungated, err := declaredOrder(m.Capabilities, name, inCatalog)
	if err != nil {
		return CapabilitySet{}, err
	}
	set := CapabilitySet{
		Shape:    m.Shape,
		Profile:  m.Profile,
		Declared: declared,
		Ungated:  ungated,
		Drivers:  cloneDrivers(m.Drivers),
	}
	// 驱动默认取 Descriptor.Drivers 首项（S4）；marker 里已有的选择原样保留。
	for _, c := range set.Declared {
		if len(set.Drivers[c]) > 0 || len(byName[c].Drivers) == 0 {
			continue
		}
		set.Drivers[c] = []string{byName[c].Drivers[0]}
	}
	return CapabilityRoots(root, set)
}

// declaredOrder 构造声明集顺序：catalog 拓扑序（catalog.All() 的顺序）+ 非 catalog（Ungated）追加在
// 尾部（沿用 marker 里的相对顺序；新能力若是 Ungated 则追加**一次**）—— 与 ParseCapabilitySet 的
// 输出口径一致。
//
// **幂等不变量**：同一名字只出现一次（marker 手改出的重复项按首次出现去重；构造结果最后再自检一遍）。
// 重复声明在生成期是**静默错误**：生成项目 build/gofmt/门禁全绿，直到进程启动
// `assembly.validateAssembly` 才报 `capability "x" declared twice` —— 必须挡在这里。
func declaredOrder(existing []string, name string, inCatalog map[string]bool) (declared, ungated []string, err error) {
	names := make(map[string]bool, len(existing)+1)
	for _, c := range existing {
		names[c] = true
	}
	names[name] = true

	emitted := make(map[string]bool, len(names))
	emit := func(n string) {
		if emitted[n] {
			return // marker 里的重复项：按首次出现去重
		}
		emitted[n] = true
		declared = append(declared, n)
	}
	for _, d := range catalog.All() {
		if names[d.Name] {
			emit(d.Name)
		}
	}
	// 非 catalog 条目：marker 已有的一次；name 只在 marker 里**还没有**时才追加 —— 这就是
	// 「Ungated 能力 + --force」曾经重复写入（声明两份/Ungated 两份）的位置。
	for _, c := range existing {
		if inCatalog[c] || !names[c] {
			continue
		}
		emit(c)
	}
	if !inCatalog[name] && !slices.Contains(existing, name) {
		emit(name)
	}
	// Ungated = 声明集里的非 catalog 条目（按声明序）：与声明集同源，不会出现「声明一份、Ungated 两份」。
	for _, n := range declared {
		if !inCatalog[n] {
			ungated = append(ungated, n)
		}
	}
	// 幂等不变量自检：构造逻辑若破线（今天这条 bug 的形状）在这里 fail-closed。
	for i, n := range declared {
		if slices.Contains(declared[i+1:], n) {
			return nil, nil, fmt.Errorf("declaration set contains capability %q twice", n)
		}
	}
	return declared, ungated, nil
}

// alreadyPresent 判定能力是否已在 entries 里：已声明，或已被某个已声明能力的 schema 依赖
// 携带（catalog.MigrationSchemaDeps 是静态表，与 CapabilityRoots 的 MigrationOnly 同源）。
func alreadyPresent(name string, declared map[string]bool) bool {
	if declared[name] {
		return true
	}
	for c := range declared {
		if slices.Contains(catalog.MigrationSchemaDeps[c], name) {
			return true
		}
	}
	return false
}

// cloneDrivers 复制 能力→驱动 映射（marker 的映射不得被就地改写）。
func cloneDrivers(in map[string][]string) map[string][]string {
	out := make(map[string][]string, len(in))
	for name, drv := range in {
		out[name] = slices.Clone(drv)
	}
	return out
}

// mergeGeneratedConfigs 落实裁定 ⑬：configs/*.yaml 与 values.yaml 以生成项目**现有**文件为底，
// 用重渲染结果补齐现有文件里没有的段/键。绝不整份覆盖 —— 那会静默抹掉用户手改的段值。
//
// 现有文件不存在时保持重渲染结果（首次生成的完整产物）。
func mergeGeneratedConfigs(dir, staging string) error {
	rels := append(configFiles(), valuesRelPath)
	for _, rel := range rels {
		existing, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(rel)))
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return fmt.Errorf("read existing %s: %w", rel, err)
		}
		freshPath := filepath.Join(staging, filepath.FromSlash(rel))
		fresh, err := os.ReadFile(freshPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue // 本选择不含该文件（如无 helm chart）
			}
			return fmt.Errorf("read rendered %s: %w", rel, err)
		}
		merged, err := MergeSectionBlocks(existing, fresh)
		if err != nil {
			return fmt.Errorf("merge %s: %w", rel, err)
		}
		if err := writeFile(freshPath, merged, 0o644); err != nil {
			return fmt.Errorf("write merged %s: %w", rel, err)
		}
	}
	return nil
}

// MergeSectionBlocks 以 base（生成项目现有内容）为底，把 fresh（蓝本重渲染的同名段）里 base
// 没有的顶层段追加进来；同名段一律用 base 原文（保住用户手改的段值），base 独有的段（用户自有）
// 也一律保留。两边的段解析都走 SectionBlocks —— 解析失败即报错，绝不静默丢内容。
//
// 接缝：base 若无尾换行（用户手改常见的形态），追加前**必须**补一个换行 —— 否则 base 末行的段值
// 会与 fresh 的首个段键粘成一行（`...持久化）# 文件存储配置`），静默毁掉两段内容。
func MergeSectionBlocks(base, fresh []byte) ([]byte, error) {
	baseKeys, baseBlocks, err := SectionBlocks(base)
	if err != nil {
		return nil, err
	}
	freshKeys, freshBlocks, err := SectionBlocks(fresh)
	if err != nil {
		return nil, err
	}
	have := make(map[string]bool, len(baseKeys))
	for _, key := range baseKeys {
		have[key] = true
	}
	var out strings.Builder
	out.Grow(len(base) + len(fresh))
	lastIsNewline := true // 空输出视为已换行：文件头不补空行
	write := func(block string) {
		if block == "" {
			return
		}
		if !lastIsNewline && block[0] != '\n' {
			out.WriteByte('\n')
		}
		out.WriteString(block)
		lastIsNewline = block[len(block)-1] == '\n'
	}
	for i := range baseKeys {
		write(baseBlocks[i])
	}
	for i, key := range freshKeys {
		if key == "" || have[key] {
			continue
		}
		write(freshBlocks[i])
	}
	return []byte(out.String()), nil
}

// changeSet 返回暂存树相对现有项目的差异（排序）：新增、内容不同、以及旧生成产物里已被移除的文件。
// 只比内容，不比 mtime —— add 的幂等判据是「逐字节等价」。`generated`（旧 marker.files）限定了
// 「移除」的候选：用户自有文件不在其中，永远不会被删除。
func changeSet(dir, staging string, generated []string) ([]string, error) {
	oldHashes, err := treeHashes(dir)
	if err != nil {
		return nil, err
	}
	newHashes, err := treeHashes(staging)
	if err != nil {
		return nil, err
	}
	gen := make(map[string]bool, len(generated))
	for _, rel := range generated {
		gen[rel] = true
	}
	var changed []string
	for rel, hash := range newHashes {
		if old, ok := oldHashes[rel]; !ok || old != hash {
			changed = append(changed, rel)
		}
	}
	for rel := range oldHashes {
		if _, ok := newHashes[rel]; !ok && gen[rel] {
			changed = append(changed, rel)
		}
	}
	sort.Strings(changed)
	return changed, nil
}

// treeHashes 返回 相对路径 → 内容 sha256。
func treeHashes(root string) (map[string]string, error) {
	out := map[string]string{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == ".git" {
				return fs.SkipDir
			}
			return nil
		}
		content, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		out[relPath(root, p)] = fmt.Sprintf("%x", sha256.Sum256(content))
		return nil
	})
	return out, err
}

// installFile 是 installStaged 的落盘注入点（测试用它注入中途失败以验证回滚）。
var installFile = copyOneFile

// installStaged 把 changed 里的文件逐个落盘：被改写/被移除的先把原文件搬进备份目录，任一失败即
// 反向回滚（恢复备份、删除本次新增），成功后删备份。**不整体 rename 项目根** —— 调用者的 cwd
// 很可能就是 <dir>（`cd proj && jimu capability add x`），目录级替换会把 shell 留在已删除的 inode 上。
func installStaged(dir, staging string, changed, generated []string) error {
	backup, err := os.MkdirTemp(filepath.Dir(dir), filepath.Base(dir)+".bak-")
	if err != nil {
		return fmt.Errorf("create backup directory: %w", err)
	}
	defer func() { _ = os.RemoveAll(backup) }()

	type op struct {
		rel     string
		restore bool // true = 原文件在备份里（回滚时恢复），false = 本次新增（回滚时删除）
	}
	var ops []op
	rollback := func() {
		for i := len(ops) - 1; i >= 0; i-- {
			o := ops[i]
			if o.restore {
				if err := copyOneFile(backup, dir, o.rel); err != nil {
					// 回滚本身失败已无法挽回：把错误留给调用方时也提示备份目录位置。
					fmt.Fprintf(os.Stderr, "rollback %s failed: %v\n", o.rel, err)
				}
				continue
			}
			_ = os.Remove(filepath.Join(dir, filepath.FromSlash(o.rel)))
		}
	}
	fail := func(format string, args ...any) error {
		rollback()
		return fmt.Errorf(format, args...)
	}

	gen := make(map[string]bool, len(generated))
	for _, rel := range generated {
		gen[rel] = true
	}
	for _, rel := range changed {
		src := filepath.Join(staging, filepath.FromSlash(rel))
		dst := filepath.Join(dir, filepath.FromSlash(rel))
		if _, err := os.Stat(src); os.IsNotExist(err) {
			if !gen[rel] {
				continue // 只删生成器产物，用户文件不在此列（changeSet 已保证）
			}
			if err := moveToBackup(dst, backup, rel); err != nil {
				return fail("remove %s: %w", rel, err)
			}
			ops = append(ops, op{rel: rel, restore: true})
			continue
		}
		existed := false
		if _, err := os.Stat(dst); err == nil {
			existed = true
			if err := copyOneFile(dir, backup, rel); err != nil {
				return fail("back up %s: %w", rel, err)
			}
		}
		if err := installFile(staging, dir, rel); err != nil {
			return fail("install %s: %w", rel, err)
		}
		ops = append(ops, op{rel: rel, restore: existed})
	}
	return nil
}

// moveToBackup 把 dst（生成项目里的相对路径）搬到备份目录的同名位置。
func moveToBackup(dst, backup, rel string) error {
	target := filepath.Join(backup, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.Rename(dst, target); err != nil {
		return err
	}
	return nil
}
