package generator

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"strconv"
	"strings"
)

// descriptorLiteral 在 AST 里定位 `var Descriptor = contract.Descriptor{...}`，返回其复合字面量。
// 找不到即报错（fail-closed：宁可不生成，也不静默漏收窄 Drivers）。
func descriptorLiteral(fset *token.FileSet, file *ast.File) (*ast.CompositeLit, error) {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) != 1 || vs.Names[0].Name != "Descriptor" || len(vs.Values) != 1 {
				continue
			}
			lit, ok := vs.Values[0].(*ast.CompositeLit)
			if !ok {
				return nil, fmt.Errorf("var Descriptor is not a composite literal")
			}
			return lit, nil
		}
	}
	return nil, fmt.Errorf("no var Descriptor composite literal found")
}

// descriptorInfo 是一份能力根包源码里的 Descriptor 视图：既能读字段字面量（S2 生成
// module.go 时搬 Owns），也能就地改写（收窄 Drivers）。
type descriptorInfo struct {
	fset  *token.FileSet
	file  *ast.File
	src   string
	lit   *ast.CompositeLit
	descr *ast.CompositeLit
}

// loadDescriptor 解析一份 Go 源码并定位 Descriptor 字面量。
func loadDescriptor(src string) (*descriptorInfo, error) {
	fset := token.NewFileSet()
	// 用 io.Reader 传源码：go/parser 的 src 参数语义陷阱 —— string/[]byte 形式**必须以换行
	// 开头**才被当作源码，否则整串被当成文件名（实测报 "file name too long"）；而加换行前缀
	// 又会让 token 偏移整体 +1，本类型用 PositionFor 反解字节区间取字面量，会取错一位。
	file, err := parser.ParseFile(fset, baseName("module"), strings.NewReader(src), parser.ParseComments)
	if err != nil {
		return nil, err
	}
	lit, err := descriptorLiteral(fset, file)
	if err != nil {
		return nil, err
	}
	// contract.Descriptor{...} 是外层 SelectorExpr 的复合字面量；裸 Descriptor{...} 也容忍。
	descr := lit
	if sel, ok := lit.Type.(*ast.SelectorExpr); ok && sel.Sel.Name != "Descriptor" {
		return nil, fmt.Errorf("var Descriptor has unexpected type")
	}
	return &descriptorInfo{fset: fset, file: file, src: src, lit: lit, descr: descr}, nil
}

// field 返回 Descriptor 字面量里某个字段的值表达式（不存在返回 nil）。
func (d *descriptorInfo) field(name string) ast.Expr {
	for _, elt := range d.descr.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		if key, ok := kv.Key.(*ast.Ident); ok && key.Name == name {
			return kv.Value
		}
	}
	return nil
}

// literal 返回某个字段的**源码字面量**（不存在返回 ""）：用于把框架仓的 Owns 原样搬进
// S2 生成的 module.go，不手写。
func (d *descriptorInfo) literal(name string) string {
	value := d.field(name)
	if value == nil {
		return ""
	}
	return d.source(value)
}

// baseName 给解析器一个不会与文件里其它位置冲突的伪文件名。
func baseName(name string) string { return "jimu_descriptor_" + name }

// source 返回某个节点在原文里的字面量。
func (d *descriptorInfo) source(node ast.Node) string {
	return d.src[d.fset.PositionFor(node.Pos(), false).Offset:d.fset.PositionFor(node.End(), false).Offset]
}

// goFileMode 是生成 .go 文件的统一权限位。
const goFileMode fs.FileMode = 0o644

// generatedHeader 是全部生成文件的统一头（S8：内容由能力集纯函数决定，手改会被重渲染覆盖）。
const generatedHeader = "// Code generated by jimu new; DO NOT EDIT.\n"

// descriptorSliceField 读框架仓某能力根包文件，取 Descriptor 里指定 []string 字段的值
// （如 Requires/Drivers）。用于把**非 catalog（Ungated）**能力的声明搬进选择集合 ——
// 这些能力不在 catalog.entries 里，只能从源码读。
func descriptorSliceField(file, field string) ([]string, error) {
	content, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}
	d, err := loadDescriptor(string(content))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", filepathSlash(file), err)
	}
	literal := d.literal(field)
	if literal == "" {
		return nil, nil
	}
	expr, err := parser.ParseExpr(literal)
	if err != nil {
		return nil, fmt.Errorf("parse Descriptor.%s of %s: %w", field, filepathSlash(file), err)
	}
	var out []string
	ast.Inspect(expr, func(n ast.Node) bool {
		lit, ok := n.(*ast.BasicLit)
		if !ok || lit.Kind != token.STRING {
			return true
		}
		if v, uerr := strconv.Unquote(lit.Value); uerr == nil {
			out = append(out, v)
		}
		return true
	})
	return out, nil
}
