package generator

import (
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestRenderCLIMainTrimsScaffoldingAndFollowsSelection 钉住生成项目 cmd/cli/main.go 的裁剪口径：
//   - 不 import 框架脚手架（tools/generator），也不注册 module create（脚手架是框架的职责）；
//   - 能力自带命令只 import/注册**已选中**能力（minimal 无 apikey → 不 import apikey/cli）。
func TestRenderCLIMainTrimsScaffoldingAndFollowsSelection(t *testing.T) {
	cases := []struct {
		name         string
		opts         NewOptions
		wantImports  []string
		wantCommands []string
	}{
		{
			name: "with user,access：无任何能力自带命令",
			opts: NewOptions{With: "user,access"},
			// migrateCmd 的五个子命令由 init 内部注册，不进 rootCmd 的直接注册集。
			wantCommands: []string{"config", "migrate", "seed", "version"},
		},
		{
			name:         "profile full：含 apikey 自带命令",
			opts:         NewOptions{Profile: "full"},
			wantImports:  []string{"example.com/proj/internal/capabilities/apikey/cli"},
			wantCommands: []string{"apikeycli.Commands()", "config", "migrate", "seed", "version"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := filepath.Join(t.TempDir(), "proj")
			tc.opts.Dir = dir
			tc.opts.Module = "example.com/proj"
			tc.opts.NoTidy = true
			_, err := NewProject(tc.opts)
			require.NoError(t, err)

			imports, commands := parseCLIMain(t, filepath.Join(dir, "cmd/cli/main.go"))
			assert.NotContains(t, imports, "example.com/proj/tools/generator", "生成项目不 import 脚手架")
			assert.NotContains(t, imports, "jimu/tools/generator")
			assert.NotContains(t, commands, "module", "生成项目不注册 module create")
			assert.NotContains(t, commands, "newCmd", "生成项目不注册脚手架命令")
			assert.ElementsMatch(t, tc.wantCommands, commands)
			for _, want := range tc.wantImports {
				assert.Contains(t, imports, want)
			}
			if len(tc.wantImports) == 0 {
				for _, imp := range imports {
					assert.NotContains(t, imp, "/cli", "未选中任何能力自带命令时不该有 /cli import：%s", imp)
				}
			}
			// 框架的脚手架命令文件整体不进生成项目。
			assert.NoFileExists(t, filepath.Join(dir, "cmd/cli/new.go"))
			assert.NoFileExists(t, filepath.Join(dir, "cmd/cli/new_test.go"))
		})
	}
}

// TestRenderCLIMainKeepsMigrationAndSeedCommands 反证裁剪没有伤到内核 CLI：
// migrate/seed/config/version 的变量声明与 init 注册都还在（否则生成项目只有空壳 CLI）。
func TestRenderCLIMainKeepsMigrationAndSeedCommands(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "proj")
	_, err := NewProject(NewOptions{Dir: dir, Profile: "minimal", Module: "example.com/proj", NoTidy: true})
	require.NoError(t, err)
	content, err := os.ReadFile(filepath.Join(dir, "cmd/cli/main.go"))
	require.NoError(t, err)
	assert.Contains(t, string(content), "// Code generated by jimu new; DO NOT EDIT.")
	for _, want := range []string{
		"var migrateCmd = &cobra.Command{", "var migrateUpCmd", "var migrateAdoptCmd",
		"var seedCmd", "var configCmd", "func main() {",
		"migrateCmd.AddCommand(migrateAdoptCmd)",
	} {
		assert.Contains(t, string(content), want)
	}
}

// parseCLIMain 解析生成项目的 cmd/cli/main.go，返回（import 路径集合，rootCmd.AddCommand 注册的
// **命令名**集合）。命令名取变量声明的 `Use:` 字段（即用户敲的那个词）；`<x>cli.Commands()...`
// 这类没有静态 Use 的参数按源码文本归一化。
func parseCLIMain(t *testing.T, path string) (imports, commands []string) {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	require.NoError(t, err)
	for _, spec := range file.Imports {
		imports = append(imports, strings.Trim(spec.Path.Value, `"`))
	}
	uses := map[string]string{}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) != 1 || len(vs.Values) != 1 {
				continue
			}
			if use := cobraUse(vs.Values[0]); use != "" {
				uses[vs.Names[0].Name] = use
			}
		}
	}
	ast.Inspect(file, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		sel, ok := call.Fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "AddCommand" {
			return true
		}
		if id, ok := sel.X.(*ast.Ident); !ok || id.Name != "rootCmd" {
			return true
		}
		arg := call.Args[0]
		if id, ok := arg.(*ast.Ident); ok {
			if use, found := uses[id.Name]; found {
				commands = append(commands, use)
			} else {
				commands = append(commands, id.Name)
			}
			return true
		}
		var buf strings.Builder
		if err := printer.Fprint(&buf, fset, arg); err != nil {
			t.Fatalf("print arg: %v", err)
		}
		commands = append(commands, buf.String())
		return true
	})
	slices.Sort(imports)
	slices.Sort(commands)
	return imports, commands
}

// cobraUse 从 `&cobra.Command{Use: "..."}` 的字面量里取 Use 字段（取不到返回 ""）。
func cobraUse(value ast.Expr) string {
	unary, ok := value.(*ast.UnaryExpr)
	if !ok {
		return ""
	}
	lit, ok := unary.X.(*ast.CompositeLit)
	if !ok {
		return ""
	}
	for _, elt := range lit.Elts {
		kv, ok := elt.(*ast.KeyValueExpr)
		if !ok {
			continue
		}
		if key, ok := kv.Key.(*ast.Ident); !ok || key.Name != "Use" {
			continue
		}
		if bl, ok := kv.Value.(*ast.BasicLit); ok && bl.Kind == token.STRING {
			return strings.Trim(bl.Value, `"`)
		}
	}
	return ""
}
