package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// pbDescriptorFixture 模拟 protoc-gen-go 的产物：raw descriptor 是**带长度前缀**的字符串字面量
// （`\x1c` = 28 = "proto/jimu/v1/userinfo.proto" 的长度）。注意这是 Go **raw string**，
// 里面的 `\x1c` 是四个字符（反斜杠+x+1+c），与 .pb.go 源文件里的写法逐字一致。
const pbDescriptorFixture = `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/jimu/v1/userinfo.proto

package userinfopb

import (
	_ "jimu/internal/capabilities/auth"

	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const file_proto_jimu_v1_userinfo_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/jimu/v1/userinfo.proto\x12\ajimu.v1\")\n" +
	"\x0eGetUserRequest"
`

// TestRewriteModuleKeepsProtobufDescriptorByteIdentical 是 C2 的核心回归：带长度前缀的
// protobuf raw descriptor 里的 `proto/jimu/...` **绝不能**被改写（长度字节不会跟着变），
// 而同一文件里的 `jimu/...` import 必须被改写。
func TestRewriteModuleKeepsProtobufDescriptorByteIdentical(t *testing.T) {
	dir := t.TempDir()
	writeTreeFile(t, dir, "go.mod", "module jimu\n\ngo 1.26.6\n")
	writeTreeFile(t, dir, "internal/capabilities/grpc/userinfopb/userinfo.pb.go", pbDescriptorFixture)

	changed, err := RewriteModule(dir, "jimu", "example.com/proj")
	require.NoError(t, err)
	assert.Contains(t, changed, "internal/capabilities/grpc/userinfopb/userinfo.pb.go")

	got, err := os.ReadFile(filepath.Join(dir, "internal/capabilities/grpc/userinfopb/userinfo.pb.go"))
	require.NoError(t, err)

	want := strings.Replace(pbDescriptorFixture,
		`"jimu/internal/capabilities/auth"`, `"example.com/proj/internal/capabilities/auth"`, 1)
	assert.Equal(t, want, string(got), "除 import 路径外必须逐字节不变")

	// 三重确认：raw descriptor 原样、且没有把 proto/ 路径改坏。
	assert.Contains(t, string(got), `\x1cproto/jimu/v1/userinfo.proto`)
	assert.NotContains(t, string(got), "proto/example.com")
	assert.NotContains(t, string(got), `"jimu/`)
}

// TestRewriteModuleOnRealProtobufDescriptor 用**仓库里真实的一份** .pb.go 做端到端回归：
// 注入一个 jimu/ import 后跑 RewriteModule，整文件除该 import 外逐字节不变 —— 覆盖真实
// protoc 产物的格式（多行 rawDesc 拼接、`\x12\ajimu.v1` 这类裸反斜杠序列）。
func TestRewriteModuleOnRealProtobufDescriptor(t *testing.T) {
	src := filepath.Join("..", "..", "internal", "capabilities", "grpc", "userinfopb", "userinfo.pb.go")
	original, err := os.ReadFile(src)
	require.NoError(t, err)
	require.Contains(t, string(original), `\x1cproto/jimu/v1/userinfo.proto`, "fixture 不再是预期的 protoc 产物")

	injected := strings.Replace(string(original),
		"import (\n", "import (\n\t_ \"jimu/internal/capabilities/auth\"\n\n", 1)
	require.NotEqual(t, string(original), injected)

	dir := t.TempDir()
	writeTreeFile(t, dir, "go.mod", "module jimu\n\ngo 1.26.6\n")
	writeTreeFile(t, dir, "internal/capabilities/grpc/userinfopb/userinfo.pb.go", injected)

	_, err = RewriteModule(dir, "jimu", "example.com/proj")
	require.NoError(t, err)

	got, err := os.ReadFile(filepath.Join(dir, "internal/capabilities/grpc/userinfopb/userinfo.pb.go"))
	require.NoError(t, err)
	want := strings.Replace(injected,
		`"jimu/internal/capabilities/auth"`, `"example.com/proj/internal/capabilities/auth"`, 1)
	assert.Equal(t, want, string(got))
	assert.Contains(t, string(got), `\x1cproto/jimu/v1/userinfo.proto`)
	assert.NotContains(t, string(got), "proto/example.com")
}

// TestRewriteModuleLeavesGoCommentsAndStringLiteralsAlone 钉住「非 import 字面量不动」：
// 注释里的路径示例、业务字符串里的 "jimu/..." 都不再被改写（它们与模块解析无关）。
func TestRewriteModuleLeavesGoCommentsAndStringLiteralsAlone(t *testing.T) {
	dir := t.TempDir()
	writeTreeFile(t, dir, "go.mod", "module jimu\n\ngo 1.26.6\n")
	writeTreeFile(t, dir, "internal/a/a.go", `// Package a —— 历史路径示例：jimu/internal/old。
package a

import (
	"jimu/internal/b"
)

// Example 注释里的 jimu/ 不动。
const example = "jimu/internal/not-an-import"
`)
	_, err := RewriteModule(dir, "jimu", "example.com/proj")
	require.NoError(t, err)
	got, err := os.ReadFile(filepath.Join(dir, "internal/a/a.go"))
	require.NoError(t, err)
	assert.Contains(t, string(got), `"example.com/proj/internal/b"`)
	assert.Contains(t, string(got), "历史路径示例：jimu/internal/old")
	assert.Contains(t, string(got), `"jimu/internal/not-an-import"`)
}

// writeTreeFile 在 root 下按相对路径写文件（自动建目录）。
func writeTreeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	require.NoError(t, os.MkdirAll(filepath.Dir(p), 0o755))
	require.NoError(t, os.WriteFile(p, []byte(content), 0o644))
}
