package main

import (
	"encoding/json"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestActiveSourceSelectsExactlyOneProfile(t *testing.T) {
	src, err := activeSource("minimal")
	require.NoError(t, err)
	assert.Contains(t, src, `"jimu/internal/profiles/minimal"`)
	assert.NotContains(t, src, `"jimu/internal/profiles/full"`)
	assert.Contains(t, src, "package active")
	assert.Contains(t, src, "func Assembly() assembly.Assembly { return minimal.Assembly() }")
	assert.Contains(t, src, "Code generated by tools/profileoverlay")

	_, err = activeSource("ghost")
	require.ErrorContains(t, err, `unknown profile "ghost"`)
}

func TestOverlayConfigPointsActiveAtTheGeneratedFile(t *testing.T) {
	root := t.TempDir()
	jsonPath, content, err := overlayConfig(root, "enterprise")
	require.NoError(t, err)
	assert.Equal(t, filepath.Join(root, ".overlay", "overlay.json"), jsonPath)

	var cfg struct{ Replace map[string]string }
	require.NoError(t, json.Unmarshal(content, &cfg))
	assert.Equal(t,
		filepath.Join(root, ".overlay", "active.go"),
		cfg.Replace[filepath.Join(root, "internal", "profiles", "active", "assembly.go")])
}

func TestOverlayConfigRejectsUnknownProfile(t *testing.T) {
	_, _, err := overlayConfig(t.TempDir(), "ghost")
	require.ErrorContains(t, err, `unknown profile "ghost"`)
}
