// Command profileoverlay 为指定形态生成 overlay 配置：把
// internal/profiles/active/assembly.go 在**本次构建**中替换为「只选该形态」的版本，
// 不改动工作区里的任何文件。
//
//	go run ./tools/profileoverlay <profile>   # 写 .overlay/{active.go,overlay.json}，打印 JSON 路径
//	go run ./tools/profileoverlay -list       # 打印全部形态名（每行一个）
//
// 用法示例：
//
//	go build -overlay=$(go run ./tools/profileoverlay minimal) -o bin/server ./cmd/server
//	go test -overlay=$(go run ./tools/profileoverlay minimal) ./internal/profiles/...
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"jimu/internal/profiles/registry"
)

// overlayDir 是生成物目录（gitignored）。
const overlayDir = ".overlay"

// activePath 是被替换的选点文件（相对仓库根）。
var activePath = filepath.Join("internal", "profiles", "active", "assembly.go")

func main() {
	if len(os.Args) == 2 && os.Args[1] == "-list" {
		fmt.Println(strings.Join(registry.Names(), "\n"))
		return
	}
	if len(os.Args) != 2 {
		fail(fmt.Errorf("用法：profileoverlay <profile> | -list"))
	}
	root, err := repoRoot()
	if err != nil {
		fail(err)
	}
	jsonPath, content, err := overlayConfig(root, os.Args[1])
	if err != nil {
		fail(err)
	}
	src, err := activeSource(os.Args[1])
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(filepath.Join(root, overlayDir, "active.go"), []byte(src), 0o644); err != nil {
		fail(err)
	}
	if err := os.WriteFile(jsonPath, content, 0o644); err != nil {
		fail(err)
	}
	fmt.Println(jsonPath)
}

func fail(err error) { fmt.Fprintln(os.Stderr, "❌ profileoverlay:", err); os.Exit(1) }

// activeSource 返回选点文件的替代内容；形态名经 registry 白名单校验。
func activeSource(profile string) (string, error) {
	if _, err := registry.Lookup(profile); err != nil {
		return "", err
	}
	return fmt.Sprintf(`// Code generated by tools/profileoverlay; DO NOT EDIT.
// 本文件是 overlay 替换版：把 internal/profiles/active 的选点指向 %s 形态。
package active

import (
	"jimu/internal/assembly"
	"jimu/internal/profiles/%s"
)

// Assembly 返回本次构建选中的形态。
func Assembly() assembly.Assembly { return %s.Assembly() }
`, profile, profile, profile), nil
}

// overlayConfig 返回 overlay JSON 的路径与其内容（键值都必须是绝对路径）。
func overlayConfig(root, profile string) (string, []byte, error) {
	if _, err := registry.Lookup(profile); err != nil {
		return "", nil, err
	}
	cfg := struct {
		Replace map[string]string `json:"Replace"`
	}{Replace: map[string]string{
		filepath.Join(root, activePath): filepath.Join(root, overlayDir, "active.go"),
	}}
	content, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return "", nil, err
	}
	if err := os.MkdirAll(filepath.Join(root, overlayDir), 0o755); err != nil {
		return "", nil, err
	}
	return filepath.Join(root, overlayDir, "overlay.json"), append(content, '\n'), nil
}

// repoRoot 从当前工作目录向上找 go.mod（make/Docker 都从仓库根调用，此处兼容子目录调用）。
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("找不到 go.mod（从 %s 向上）", dir)
		}
		dir = parent
	}
}
